# 텐서플로우 훑어보기


## 텐서와 연산

In [2]:
import numpy as np
import tensorflow as tf

/Users/barrett11357/coding/pycharm/handson_ml_--/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


텐서플로우 API는 텐서를 순환시킨다. 텐서는 넘파이 ndadday와 매우 비슷하다. 즉 텐서는 일반적으로 다차원 배열이다. 하지만 스칼라 값도 가질 수 있다.

사용자 정의 함수, 사용자 정의 지표, 사용자 정의 층 등을 만들 때 텐서가 중요하다.



`tf.constant()`함수로 텐서를 만들 수 있다.

In [3]:
# 실수 값을 가지는 2행 3열의 텐서
# ndarray와 마찬가지로 shape와 dtype을 가진다.

t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(t)
print(t.shape)
print(t.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


2025-02-06 02:56:18.909409: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-02-06 02:56:18.909459: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-02-06 02:56:18.909466: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-02-06 02:56:18.909667: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-02-06 02:56:18.909683: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


인덱스 참조도 ndarray와 매우 비슷하게 작동한다.

In [4]:
print(t[:, 1:]) # 모든 행애서 1열 이상의 값만 슬라이싱
print(t[:, 1:, tf.newaxis]) # 새로운 차원을 추가

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[2.]
  [3.]]

 [[5.]
  [6.]]], shape=(2, 2, 1), dtype=float32)


모든 종류의 텐서 연산이 가능하다. 쉽게 말해 행렬연산이 된다 이 얘기다.

In [5]:
print(t+10)
print(tf.square(t))
print(t @ tf.transpose(t)) # 전치 후 행렬 곱 수행

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


텐서는 스칼라 값도 가질 수 있다.

In [6]:
tf.constant(42) # 이 경우 크기는 비어있다.

<tf.Tensor: shape=(), dtype=int32, numpy=42>

필요한 모든 기본 수학 연산과 넘파이에서 볼 수 있는 대부분의 연산을 제공한다. 일부 함수들은 넘파이와 이름이 다르다. (근데 나는 넘파이 함수도 잘 모름ㅋㅋ)

텐서플로의 텐서는 넘파이와 한가지 중요한 차이점이 있는데 텐서플로에서는 전치된 데이터의 복사본으로 새로운 텐서가 만들어지지만, 넘파이에서는 t.T는 동일한 데이터의 전치된 뷰일 뿐이다.

## 텐서와 넘파이

텐서와 넘파이는 함께 사용하기 편리하다. 넘파이 배열로 텐서를 만들 수 있고, 그 반대도 가능하다. 넘파이 배열에 텐서플로 연산을 적용할 수 있고, 그 반대도 가능하다.

In [7]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a)

print(tf.constant(a)) # 넘파이 배열로 텐서를 만들 수도 있다.

print(np.array(t)) # 반대로 텐서로 넘파이 배열을 만들 수도 있다.

print(tf.square(a)) # 서로 상대의 연산을 이용할 수 있음.
print(np.square(t))

[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float64)
[[ 1.  4.  9.]
 [16. 25. 36.]]


## 타입 변환

텐서플로는 어떠한 타입변환도 자동으로 수행하지 않는다. 서로 다른 타입끼리 연산하려고 하면 예외 터뜨림.

변환이 필요할 때는 `tf.cast()`함수를 사용하면 된다.

## 변수

지금까지 살펴본 tf.Tensor는 변경이 불가능한 불변 객체다. 즉 텐서의 내용을 바꿀 수가 없다. 그래서 일반적인 텐서로는 역전파로 변경되어야 하는 신경망의 가중치를 구현할 수 없음.

이것이 `tf.Variable`이 필요한 이유다.

기본적으로는 텐서와 비슷하게 작동한다. 하지만 `assign()`메서드를 사용해서 변숫값을 바꿀 수 있다. 혹은 `scatter_update(), scatter_nd_update()`메서드를 사용해서 개별 원소를 수정할 수도 있다.

In [8]:
v = tf.Variable([[1,2,3], [4,5,6]])
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [9]:
v.assign(v*2)
print(v) # 가변 객체의 성질을 확인할 수 있다.

v[0,0].assign(100)
print(v)

v[:, 2].assign([1,1])
print(v)

# 직접 수정은 안된다.
v[0] = [4,5,6]

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   6],
       [  8,  10,  12]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   1],
       [  8,  10,   1]], dtype=int32)>


TypeError: 'ResourceVariable' object does not support item assignment

실전에서 변수를 직접 만들고 수동으로 값을 업데이트 하는 일은 매우 드물 것이라고 함.

# 사용자 정의 모델과 훈련 알고리즘

## 사용자 정의 손실 함수(후버손실 구현)

**후버** 손실을 직접 구현해보자. 그냥 keras.losses에 있는걸 갖다 써도 되긴 하는데 연습차 직접 구현해보는 것이다.

처음에는 단순한 방식으로 구현해보고 문제점을 파악하면서 리팩토링 해볼 것이다. 일단 얘만 좀 복잡하게 설명하면서 하면 나머지들은 거의 비슷함.

후버 손실은 MSE와 MAE를 결합한 손실함수다. 구조는 매우 단순한데 임계값을 기준으로 손실이 작으면 MSE, 손실이 크면 MAE를 적용한다. 이게 끝이다.

레이블과 모델의 예측을 매개변수로 받는 함수를 만들고, 텐서플로 연산을 사용해서 **각 샘플의 손실을 모두 담은 텐서를 계산하면 된다.**

In [12]:
def hubber_fn(label, y_predict):
    error = label - y_predict # 손실 텐서
    is_small_error = tf.abs(error) < 1 # 손실이 임계값 1보다 작은지 기록한 이진 벡터
    squared_loss = tf.square(error)/2 # MSE 계산
    linear_loss = tf.abs(error) - 0.5 # MAE 계산
    return tf.where(is_small_error, squared_loss, linear_loss) # tf.where()조건부 선택 함수, True면 앞의 값, False면 뒤의 값을 선택

중요! **성능을 생각한다면 이 코드와 같이 반복문을 사용하지 않고 벡터화해서 구현해야 한다고 한다. 그리고 텐서플로 그래프 최적화의 장점을 사용하려면 텐서플로 연산만 사용해야 한다고 한다.**

이제 이 손실함수를 사용해서 모델을 컴파일 할 수 있다. 이게 끝이다!!

In [16]:
model = tf.keras.Model()
model.compile(loss=hubber_fn, optimizer='sgd')

### 사용자 정의 요소를 가진 모델을 저장하고 로드하기

모델을 저장하는건 아무 문제 없는데, 문제는 로드할 때다. 사용자 정의 요소의 이름과 객체를 매핑한 딕셔너리를 로드 함수의 매개변수로 넣어줘야 한다. 아니면 데코레이터를 붙여줘도 된다. 챕터10의 서브클래싱 API를 사용할 때 똑같은 일을 겪었음.

In [17]:
model.save('my_model_with_custom_loss.keras') # 그냥 하면 됨.

In [18]:
model = tf.keras.models.load_model('my_model_with_custom_loss.keras', custom_objects={'hubber_fn': hubber_fn}) # 이렇게 해줘야 한다.

### 손실 함수가 매개변수를 받게 하자

losses.Loss클래스를 상속한 클래스를 만들고 call(), get_config()메서드를 구현하면 된다. 이게 진짜 좀 제대로 만드는 느낌쓰

In [22]:
class HuberLoss(tf.keras.losses.Loss):
    def __init__(self, threshold=1.0, **kwargs):
        super().__init__(**kwargs) # 기본적인 하이퍼파라미터를 **kwargs로 받은 매개변수 값을 부모 클래스의 생성자에 전달
        self.threshold = threshold

    # 이 메서드는 앞에서 만든 huber_fn 함수와 똑같다.
    def call(self, label, y_predict):
        error = label - y_predict # 손실 텐서
        is_small_error = tf.abs(error) < self.threshold # 손실이 임계값 1보다 작은지 기록한 이진 벡터
        squared_loss = tf.square(error)/2 # MSE 계산
        linear_loss = tf.abs(error) - 0.5 # MAE 계산
        return tf.where(is_small_error, squared_loss, linear_loss) # tf.where()조건부 선택 함수, True면 앞의 값, False면 뒤의 값을 선택

    # 이 메서드는 커스텀 클래스의 직렬화와 관련된 중요한 역할을 한다.
    # 하이퍼파라미터 이름과 같이 매핑된 딕셔너리를 반환한다. 설정 정보를 반환해서 나중에 모델을 저장하고 다시 저장할 떄 필요한 정보를 저장하는 역할을 한다.
    def get_config(self):
        base_config = super().get_config() # 먼저 부모클래스의 get_config()메서드를 호출하고, 그 다음 반환된 딕셔너리에 새로운 하이퍼파라미터를 추가한다.
        return {**base_config, 'threshold': self.threshold}

이제 모델을 컴파일 할 때 이 모델의 인스턴스를 사용하면 된다. **그리고 이제 모델을 저장할 떄 하이퍼파라미터(여기에서는 임계값)도 함께 저장된다.**

In [29]:
model.compile(loss=HuberLoss(threshold=1.7), optimizer='sgd')
model.save("my_model_with_custom_loss.keras")
model = tf.keras.models.load_model("my_model_with_custom_loss.keras", custom_objects={'HuberLoss': HuberLoss})

In [30]:
print(model.loss.threshold) # 모델의 임계값이 저장된 것을 확인할 수 있다.

1.7
